import { chromium } from 'playwright'
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
const logs = []
page.on('console', (msg) => logs.push(`[${msg.type()}] ${msg.text()}`))
page.on('pageerror', (err) => logs.push(`[pageerror] ${String(err)}`))
await page.goto('http://127.0.0.1:3090/', { waitUntil: 'domcontentloaded', timeout: 30000 })
await page.waitForTimeout(6000)
await page.getByText('Skill 商店', { exact: true }).first().click()
await page.waitForTimeout(1200)
console.log('--- BEFORE REFRESH ---')
console.log((await page.evaluate(() => document.body.innerText)).slice(0, 800))
await page.getByRole('button', { name: '刷新' }).click()
await page.waitForTimeout(3000)
console.log('--- AFTER REFRESH ---')
console.log((await page.evaluate(() => document.body.innerText)).slice(0, 1200))
console.log('--- CONSOLE ---')
console.log(logs.slice(0, 20).join('\n'))
await page.screenshot({ path: 'D:/桌面/振翅新科/_debug_market.png', fullPage: true })
await browser.close()