import { chromium } from 'playwright'
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
const errors = []
page.on('console', (msg) => { const t = msg.text(); if (msg.type() === 'error' || /slot|model|permission|fail|error/i.test(t)) errors.push(`[${msg.type()}] ${t.slice(0, 300)}`) })
page.on('pageerror', (err) => errors.push(`[pageerror] ${String(err).slice(0, 300)}`))
await page.goto('http://127.0.0.1:3090/', { waitUntil: 'domcontentloaded', timeout: 30000 })
await page.waitForTimeout(6000)
let body = await page.evaluate(() => document.body.innerText)
console.log('--- page text (first 800) ---')
console.log(body.slice(0, 800))
console.log('--- checks ---')
for (const c of ['模型', '权限', '访问', '对话', '新建', 'Workspace', '开始']) console.log(`${c}: ${body.includes(c) ? 'OK' : 'MISSING'}`)
await page.screenshot({ path: 'D:/桌面/振翅新科/_diag_inputbar_home.png', fullPage: false })
console.log('--- console errors ---')
console.log(errors.length ? errors.slice(0, 15) : 'none')
await browser.close()
