import { chromium } from 'playwright'
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
const errors = []
page.on('console', (msg) => { const t = msg.text(); if (msg.type() === 'error') errors.push(`[err] ${t.slice(0, 300)}`) })
page.on('pageerror', (err) => errors.push(`[pageerror] ${String(err).slice(0, 300)}`))
page.on('filechooser', (fc) => errors.push(`[filechooser] ${fc.element() ? 'element' : ''}`))
page.on('dialog', async (d) => { errors.push(`[dialog] ${d.type()} ${d.message().slice(0,100)}`); await d.dismiss().catch(()=>{}) })
await page.goto('http://127.0.0.1:3090/', { waitUntil: 'domcontentloaded', timeout: 30000 })
await page.waitForTimeout(5000)
await page.getByText('选择工作区', { exact: true }).first().click()
await page.waitForTimeout(3000)
const html = await page.evaluate(() => document.body.innerText)
console.log('--- after click (3s) ---')
console.log(html.slice(0, 600))
console.log('--- inputs/selects count ---')
console.log(await page.locator('input, select, textarea').count())
console.log('--- events/errors ---')
console.log(errors.length ? errors.slice(0, 15) : 'none')
await page.screenshot({ path: 'D:/桌面/振翅新科/_diag_ws2.png' })
await browser.close()
