import { chromium } from 'playwright'
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
page.on('console', (msg) => { if (msg.type() === 'error') errors.push(msg.text()) })
page.on('pageerror', (err) => errors.push(String(err)))
await page.goto('http://127.0.0.1:3090/', { waitUntil: 'domcontentloaded', timeout: 30000 })
await page.waitForTimeout(5000)
// hero copy
const body0 = await page.evaluate(() => document.body.innerText)
console.log('HERO has 蝴蝶振翅，一念换天:', body0.includes('蝴蝶振翅，一念换天'))
await page.getByText('设置', { exact: true }).first().click()
await page.waitForTimeout(1200)
await page.getByText('Skill 商店', { exact: true }).click()
await page.waitForTimeout(1500)
const text = await page.evaluate(() => document.body.innerText)
console.log('=== SKILL STORE SECTION ===')
const start = text.indexOf('Skill 商店')
console.log(text.slice(start, start + 1800))
console.log('=== CONSOLE ERRORS ===')
console.log(errors.length ? errors.slice(0, 10) : 'none')
await page.screenshot({ path: 'D:/桌面/振翅新科/_verify_store.png' })
await browser.close()
