import { chromium } from 'playwright'
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
const errors = []
page.on('console', (msg) => { if (msg.type() === 'error') errors.push(msg.text()) })
page.on('pageerror', (err) => errors.push(String(err)))
await page.goto('http://127.0.0.1:3090/', { waitUntil: 'domcontentloaded', timeout: 30000 })
await page.waitForTimeout(6000)
await page.getByText('Skill 商店', { exact: true }).first().click()
await page.waitForTimeout(1200)
await page.getByRole('button', { name: '工坊', exact: true }).click()
await page.waitForTimeout(1500)
const body = await page.evaluate(() => document.body.innerText)
console.log(`创建卡文案更新: ${body.includes('对话中创建新技能') ? 'OK' : 'FAIL'}`)
console.log(`旧文案已移除: ${!body.includes('对话式创建 / 再训练') ? 'OK' : 'FAIL'}`)
console.log('=== CONSOLE ERRORS ===')
console.log(errors.length ? errors.slice(0, 10) : 'none')
await browser.close()