import { chromium } from 'playwright'
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
const errors = []
page.on('console', (msg) => { if (msg.type() === 'error') errors.push(msg.text()) })
page.on('pageerror', (err) => errors.push(String(err)))
await page.goto('http://127.0.0.1:3090/', { waitUntil: 'domcontentloaded', timeout: 30000 })
await page.waitForTimeout(6000)
await page.getByText('Skill 商店', { exact: true }).first().click()
await page.waitForTimeout(1200)
await page.getByRole('button', { name: '工坊', exact: true }).click()
await page.waitForTimeout(1500)

const row = page.locator('li', { hasText: 'SQE客诉处理' })
await row.getByRole('button', { name: '再训练', exact: true }).click()
await page.waitForTimeout(800)
let body = await page.evaluate(() => document.body.innerText)
console.log(`再训练聚焦提示: ${body.includes('当前目标技能：/sqe-8d') ? 'OK' : 'FAIL'}`)

await row.getByRole('button', { name: '版本历史', exact: true }).click()
await page.waitForTimeout(800)
body = await page.evaluate(() => document.body.innerText)
console.log(`版本历史展开: ${body.includes('版本历史') && body.includes('暂无历史版本') ? 'OK' : 'FAIL'}`)
await page.screenshot({ path: 'D:/桌面/振翅新科/_verify_workshop_retrain.png', fullPage: true })
console.log('=== CONSOLE ERRORS ===')
console.log(errors.length ? errors.slice(0, 10) : 'none')
await browser.close()