import { chromium } from 'playwright'
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
const errors = []
page.on('console', (msg) => { if (msg.type() === 'error') errors.push(msg.text()) })
page.on('pageerror', (err) => errors.push(String(err)))
const step = (name, ok) => console.log(`${ok ? 'OK  ' : 'FAIL'} ${name}`)
let failed = false

await page.goto('http://127.0.0.1:3090/', { waitUntil: 'domcontentloaded', timeout: 30000 })
await page.waitForTimeout(6000)

// --- Settings page ---
await page.getByText('设置', { exact: true }).first().click()
await page.waitForTimeout(1200)
await page.getByText('Skill 设置', { exact: true }).click()
await page.waitForTimeout(1500)
let body = await page.evaluate(() => document.body.innerText)
step('设置页有视觉配置卡', body.includes('视觉识别生成（预留）') && body.includes('视觉模型地址'))
step('设置页有已安装技能列表', body.includes('已安装技能'))
step('设置页有保存设置按钮', await page.getByRole('button', { name: '保存设置' }).count() === 1)
step('设置页无导入按钮', (await page.getByRole('button', { name: '导入技能' }).count()) === 0)
step('设置页无导出按钮', (await page.getByRole('button', { name: '导出 .md' }).count()) === 0)
step('设置页无版本历史按钮', (await page.getByRole('button', { name: '版本历史' }).count()) === 0)
step('设置页无再训练按钮', (await page.getByRole('button', { name: '再训练', exact: true }).count()) === 0)
step('设置页无移除按钮', (await page.getByRole('button', { name: '移除' }).count()) === 0)
step('设置页勾选可用(人格)', (await page.locator('input[type="checkbox"]').count()) >= 5)

// Close settings, open the skill center workshop via the hero card.
await page.keyboard.press('Escape')
await page.waitForTimeout(800)
await page.getByText('Skill 商店', { exact: true }).first().click()
await page.waitForTimeout(1200)
await page.getByRole('button', { name: '工坊', exact: true }).click()
await page.waitForTimeout(1500)
body = await page.evaluate(() => document.body.innerText)
step('工坊有已安装技能列表', body.includes('已安装技能'))
step('工坊行有复制命令', body.includes('复制 /sqe-8d'))
step('工坊行有导出 .md', body.includes('导出 .md'))
step('工坊行有导出 .json', body.includes('导出 .json'))
step('工坊行有版本历史', body.includes('版本历史'))
step('工坊行有再训练', body.includes('再训练'))
step('工坊行有移除', body.includes('移除'))
step('工坊有对话式创建卡', body.includes('对话式创建 / 再训练'))
step('工坊有导入卡', body.includes('导入本地技能文件'))
step('工坊有视觉预留卡', body.includes('视频 / 摄像头识别生成（预留）'))
step('工坊无保存设置按钮', (await page.getByRole('button', { name: '保存设置' }).count()) === 0)

console.log('=== CONSOLE ERRORS ===')
console.log(errors.length ? errors.slice(0, 10) : 'none')
if (errors.length > 0) failed = true
await page.screenshot({ path: 'D:/桌面/振翅新科/_verify_workshop_split.png', fullPage: true })
await browser.close()
console.log(failed ? 'RESULT: FAIL' : 'RESULT: PASS')
process.exit(failed ? 1 : 0)