import { chromium } from 'playwright'
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
page.on('console', (msg) => { if (msg.type() === 'error') errors.push(msg.text()) })
page.on('pageerror', (err) => errors.push(String(err)))
await page.goto('http://127.0.0.1:3090/', { waitUntil: 'domcontentloaded', timeout: 30000 })
await page.waitForTimeout(5000)
await page.getByText('设置', { exact: true }).first().click()
await page.waitForTimeout(1200)
await page.getByText('Skill 商店', { exact: true }).click()
await page.waitForTimeout(1500)
const body0 = await page.evaluate(() => document.body.innerText)
console.log('has 文本技能 badge:', body0.includes('文本技能'))
console.log('has 对话中启用（人格）:', body0.includes('对话中启用（人格）'))
console.log('has 保存设置:', body0.includes('保存设置'))
// toggle first checkbox (SQE客诉处理 row) and save
const row = page.locator('li').filter({ hasText: 'SQE客诉处理' }).first()
await row.locator('input[type="checkbox"]').check()
await page.waitForTimeout(300)
console.log('dirty badge visible:', await page.getByText('有未保存的改动').isVisible().catch(() => false))
await page.getByText('保存设置', { exact: true }).click()
await page.waitForTimeout(1200)
const body1 = await page.evaluate(() => document.body.innerText)
console.log('saved ok notice:', body1.includes('设置已保存。'))
console.log('=== CONSOLE ERRORS ===')
console.log(errors.length ? errors.slice(0, 10) : 'none')
await page.screenshot({ path: 'D:/桌面/振翅新科/_verify_persona.png' })
await browser.close()
